project:
  type: website

website:
  title: "Quarto Template"
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/jbenavidest/JuanPBT
  sidebar:
    - logo: features/images/exeter.png
      contents:
        - text: Overview
          href: index.qmd

format:
  html:
    theme: default