project:
  type: website
  output-dir: docs

description-meta: "Research website about Juan Pablo Benavides-Tocarruncho"
author-meta: "Juan Benavides-Tocarruncho"

website:
  title: "Juan Benavides-Tocarruncho"
  image: files/images/exeter.png
  description: "Research website about Juan Pablo Benavides-Tocarruncho"
  
  navbar:
    background: light
    left:
      #- text: Home
      #  href: index.qmd
      - text: Contact
        href: pages/contact.qmd
        #menu:
          # - text: Contact
          # - text: News
          #   href: pages/posts.qmd#category=news
          # - text: Events
          #   href: pages/posts.qmd#category=event
      - text: Research
        href: pages/publications.qmd
#          - text: Grants
#            href: pages/projects.qmd
      - text: Outreach
        href: pages/SciComm.qmd
        #menu:
          #- text: Presentations
          #  href: pages/posts.qmd#category=presentation
          #- text: Science communication
      - text: Group
        href: https://sites.exeter.ac.uk/lucyrowland/
        target: _blank
    right:
      - text: CV
        href: files/CV-JuanPablo_Benavides-Tocarruncho.pdf
      - icon: github
        href: https://github.com/jbenavidest
        target: _blank

  page-footer:
 #   left: "[Juan P. Benavies-T](http://www.github.com/jbenavidest) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: "Built with [Quarto](https://quarto.org)"
  site-url: "https://jbenavidest.github.io"

  page-navigation: true
  search: true
  reader-mode: true
  draft-mode: unlinked
  open-graph: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: false
    link-external-newwindow: true
    email-obfuscation: javascript